redash:
  image: redash/redash:latest
  ports:
    - "5000:5000"
  links:
    - redis
  environment:
    REDASH_LOG_LEVEL: "INFO"
    REDASH_REDIS_URL: "redis://redis:6379/0"
    REDASH_DATABASE_URL: "postgresql://postgres@192.168.33.60/postgres"
    REDASH_COOKIE_SECRET: veryverysecret
redis:
  image: redis:2.8
redash-nginx:
  image: redash/nginx:latest
  ports:
    - "80:80"
  links:
    - redash
